"use client";

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import { CalculationResult } from "@/types";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Helvetica",
    fontSize: 10,
  },
  header: {
    marginBottom: 30,
    borderBottom: "2px solid #1a1a1a",
    paddingBottom: 15,
  },
  title: {
    fontSize: 22,
    fontFamily: "Helvetica-Bold",
    color: "#1a1a1a",
  },
  subtitle: {
    fontSize: 11,
    color: "#666",
    marginTop: 4,
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    marginBottom: 10,
    color: "#1a1a1a",
    borderBottom: "1px solid #e5e5e5",
    paddingBottom: 5,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 4,
    borderBottom: "0.5px solid #f0f0f0",
  },
  rowLabel: {
    fontSize: 10,
    color: "#333",
  },
  rowValue: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: "#1a1a1a",
  },
  subRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 3,
    paddingLeft: 15,
  },
  subRowLabel: {
    fontSize: 9,
    color: "#666",
  },
  subRowValue: {
    fontSize: 9,
    color: "#666",
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderTop: "2px solid #1a1a1a",
    marginTop: 10,
  },
  totalLabel: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    color: "#1a1a1a",
  },
  totalValue: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    color: "#1a1a1a",
  },
  infoBox: {
    backgroundColor: "#f8f8f8",
    padding: 12,
    borderRadius: 4,
    marginBottom: 20,
  },
  infoRow: {
    flexDirection: "row",
    marginBottom: 4,
  },
  infoLabel: {
    fontSize: 9,
    color: "#666",
    width: 120,
  },
  infoValue: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: "#333",
  },
  disclaimer: {
    marginTop: 30,
    padding: 10,
    backgroundColor: "#fffbeb",
    borderRadius: 4,
  },
  disclaimerText: {
    fontSize: 8,
    color: "#92400e",
    lineHeight: 1.4,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 8,
    color: "#999",
    borderTop: "0.5px solid #e5e5e5",
    paddingTop: 10,
  },
});

function formatCurrency(amount: number): string {
  return `$${amount.toLocaleString("en-US")}`;
}

interface PdfReportProps {
  result: CalculationResult;
}

export function PdfReport({ result }: PdfReportProps) {
  const { input, breakdown, totalLandedCost, cifValue, estimatedTransitDays } = result;
  const totalMods = breakdown.modifications.reduce((s, m) => s + m.amount, 0);
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Import Cost Estimate</Text>
          <Text style={styles.subtitle}>
            Generated by CrossBorder Navigator on {date}
          </Text>
        </View>

        <View style={styles.infoBox}>
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Item Type:</Text>
            <Text style={styles.infoValue}>
              {input.itemType.charAt(0).toUpperCase() + input.itemType.slice(1)}
            </Text>
          </View>
          {input.vehicleMake && (
            <View style={styles.infoRow}>
              <Text style={styles.infoLabel}>Vehicle:</Text>
              <Text style={styles.infoValue}>
                {input.vehicleYear} {input.vehicleMake} {input.vehicleModel} {input.vehicleTrim || ""}
              </Text>
            </View>
          )}
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Origin:</Text>
            <Text style={styles.infoValue}>
              {input.originRegion}, {input.originCountry === "US" ? "United States" : "Canada"}
            </Text>
          </View>
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Destination:</Text>
            <Text style={styles.infoValue}>
              {input.destinationCity}, {input.destinationCountry}
            </Text>
          </View>
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Shipping Method:</Text>
            <Text style={styles.infoValue}>
              {input.shippingMethod === "roro" ? "Roll-on/Roll-off (RoRo)" : "Container (20/40ft)"}
            </Text>
          </View>
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Est. Transit Time:</Text>
            <Text style={styles.infoValue}>
              {estimatedTransitDays.min}-{estimatedTransitDays.max} days
            </Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Cost Breakdown</Text>

          <View style={styles.row}>
            <Text style={styles.rowLabel}>Base Item Price</Text>
            <Text style={styles.rowValue}>{formatCurrency(breakdown.basePrice)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.rowLabel}>
              International Shipping ({input.shippingMethod === "roro" ? "RoRo" : "Container"})
            </Text>
            <Text style={styles.rowValue}>{formatCurrency(breakdown.shipping)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.rowLabel}>Marine Insurance (1.5% CIF)</Text>
            <Text style={styles.rowValue}>{formatCurrency(breakdown.insurance)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.rowLabel}>CIF Value</Text>
            <Text style={styles.rowValue}>{formatCurrency(cifValue)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.rowLabel}>Customs Duty (5% CIF)</Text>
            <Text style={styles.rowValue}>{formatCurrency(breakdown.customsDuty)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.rowLabel}>VAT</Text>
            <Text style={styles.rowValue}>{formatCurrency(breakdown.vat)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.rowLabel}>Port Handling & Clearance</Text>
            <Text style={styles.rowValue}>{formatCurrency(breakdown.portHandling)}</Text>
          </View>

          {breakdown.modifications.length > 0 && (
            <>
              <View style={styles.row}>
                <Text style={styles.rowLabel}>Required Modifications</Text>
                <Text style={styles.rowValue}>{formatCurrency(totalMods)}</Text>
              </View>
              {breakdown.modifications.map((mod) => (
                <View key={mod.label} style={styles.subRow}>
                  <Text style={styles.subRowLabel}>{mod.label}</Text>
                  <Text style={styles.subRowValue}>{formatCurrency(mod.amount)}</Text>
                </View>
              ))}
            </>
          )}

          <View style={styles.row}>
            <Text style={styles.rowLabel}>Documentation & Processing</Text>
            <Text style={styles.rowValue}>{formatCurrency(breakdown.documentation)}</Text>
          </View>

          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>TOTAL ESTIMATED LANDED COST</Text>
            <Text style={styles.totalValue}>{formatCurrency(totalLandedCost)}</Text>
          </View>
        </View>

        <View style={styles.disclaimer}>
          <Text style={styles.disclaimerText}>
            DISCLAIMER: {result.disclaimer}
          </Text>
        </View>

        <Text style={styles.footer}>
          CrossBorder Navigator | crossbordernavigator.com | This document is for informational purposes only.
        </Text>
      </Page>
    </Document>
  );
}
